name       : libjpeg-turbo6
version    : 1.5.1
release    : 7
source     :
    - https://vorboss.dl.sourceforge.net/project/libjpeg-turbo/1.5.1/libjpeg-turbo-1.5.1.tar.gz : 41429d3d253017433f66e3d472b8c7d998491d2f41caa7306b8d9a6f2a2c666c
homepage   : http://sourceforge.net/projects/libjpeg-turbo/
license    :
    - BSD-3-Clause
summary    : libjpeg-turbo is a a fork of the original IJG libjpeg, offering faster compression and decompression.
component  : desktop.library
optimize   : speed
emul32     : yes
description: |
    libjpeg-turbo is a fork of the original IJG libjpeg which uses SIMD to accelerate baseline JPEG compression and decompression. libjpeg is a library that implements JPEG image encoding, decoding and transcoding.
setup      : |
    %configure --prefix=/usr \
                --mandir=/usr/share/man \
                --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/include
    rm -rf $installdir/usr/share
    rm -rf $installdir/usr/bin
    rm -rf $installdir/%libdir%/*.so
    rm -rf $installdir/%libdir%/libturbo*
    rm -rf $installdir/%libdir%/pkgconfig
